mulgara.server=<rmi://localhost/cone#>
mulgara.model.type=<http://mulgara.org/mulgara#Model>
mulgara.lucene.model.type=<http://mulgara.org/mulgara#LuceneModel>
mulgara.rdffile.path=c:\\data\\AFDB\\1111_journals.rdf
journal.model=<rmi://localhost/cone#jnar>
journal.lucene=<rmi://localhost/cone#jnar_all>
journal.alternatives=<rmi://localhost/cone#jnar_altTitle>
journal.identifiers=<rmi://localhost/cone#jnar_issn>
journal.publishers=<rmi://localhost/cone#jnar_publisher>
journal.rights=<rmi://localhost/cone#jnar_right>
journal.subjects=<rmi://localhost/cone#jnar_subject>
journal.titles=<rmi://localhost/cone#jnar_title>
dc.identifier.urn=<http://purl.org/dc/elements/1.1/identifier>
dc.title.urn=<http://purl.org/dc/elements/1.1/title>
dc.publisher.urn=<http://purl.org/dc/elements/1.1/publisher>
dc.rights.urn=<http://purl.org/dc/elements/1.1/rights>
dc.subject.urn=<http://purl.org/dc/elements/1.1/subject>
dc.alternative.urn=<http://purl.org/dc/terms/alternative>